name: aula-v2

include:
  # aula-backend-legacy service & aula_local network
  - ./legacy/docker-compose.yml

services:
  aula-backend.v2:
    build:
      context: ./
      args:
        - DOCKER_TAG=local
    ports:
      - "8000:80"
    environment:
      DB_HOST: mariadb
      DB_PORT: "3306"
      CENTRAL_DB_HOST: ${CENTRAL_DB_HOST:-mariadb}
      CENTRAL_DB_PORT: ${CENTRAL_DB_PORT:-3306}
      CENTRAL_DB_NAME: ${CENTRAL_DB_NAME:-aula_database}
      CENTRAL_DB_USER: ${CENTRAL_DB_USER:-aula_user}
      CENTRAL_DB_PASS: ${CENTRAL_DB_PASS:-example}
       # OpenTelemetry
      OTEL_SERVICE_NAME: ${OTEL_SERVICE_NAME:-aula-backend}
      OTEL_TRACES_EXPORTER: ${OTEL_TRACES_EXPORTER:-otlp}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:-http://otel-collector:4318}
      OTEL_EXPORTER_OTLP_PROTOCOL: ${OTEL_EXPORTER_OTLP_PROTOCOL:-http/protobuf}
    volumes:
      - type: bind
        source: ./app
        target: /opt/laravel/app
        bind:
          create_host_path: false
      - type: bind
        source: ./config
        target: /opt/laravel/config
        bind:
          create_host_path: false
      - type: bind
        source: ./routes
        target: /opt/laravel/routes
        bind:
          create_host_path: false
      - type: bind
        source: ./database
        target: /opt/laravel/database
        bind:
          create_host_path: false
      - type: bind
        source: ./.env
        target: /opt/laravel/.env
        bind:
          create_host_path: false
      - type: bind
        source: ./storage/oauth-private.key
        target: /opt/laravel/storage/oauth-private.key
        bind:
          create_host_path: false
      - type: bind
        source: ./storage/oauth-public.key
        target: /opt/laravel/storage/oauth-public.key
        bind:
          create_host_path: false
      - type: bind
        source: ./legacy/docker-local/_generated_files_data/
        target: /mnt/aula-backend-legacy/files
        bind:
          create_host_path: true
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - aula_local

  nginx:
    image: nginx:stable-alpine-slim
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx-reverse-proxy.conf:/etc/nginx/nginx.conf
    networks:
      - aula_local

  # a mariadb instance is included here as a docker service, in case you need it
  mariadb:
    image: mariadb:11.7
    ports:
      - "3307:3306"
    environment:
      # @NOTE: if you use this container, these
      #  values need to be reflected in .env
      MARIADB_DATABASE: aula_database
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: aula_user
      MARIADB_PASSWORD: example
    volumes:
      - ./docker/mariadb/:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - aula_local

  redis:
    image: redis:latest
    ports:
      - 6380:6379
    networks:
      - aula_local
